# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gprd_predict <- function(outcome, training_cases, test_cases, B, b, cov_sigma, cov_ell, obs_sigma) {
    .Call(`_gprd_predict`, outcome, training_cases, test_cases, B, b, cov_sigma, cov_ell, obs_sigma)
}

